# Generated by Django 4.2.4 on 2023-09-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('posicion', models.IntegerField(choices=[(1, 'arquero'), (2, 'defensor'), (3, 'Defensor'), (4, 'Defensor'), (5, 'Defensor'), (6, 'Mediocampista'), (7, 'Mediocampista'), (8, 'Mediocampista'), (9, 'Delantero'), (10, 'Delantero'), (11, 'Delantero')])),
            ],
        ),
    ]
