# Generated by Django 4.2.4 on 2023-09-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.IntegerField(choices=[(1, 'Arquero'), (2, 'Central'), (3, 'Lateral_izq'), (4, 'Lateral_der'), (5, 'Mediocentro'), (6, 'Defensor'), (7, 'wing_derecho'), (8, 'Mediocampista'), (9, 'Delantero'), (10, 'Enganche'), (11, 'wing_izquierdo')], unique=True),
        ),
    ]
